package Constructor;

public class Test {
    public void wish(){
        System.out.println("wish");
    }
// Default constructor : generated by compiler: 0 arg constructor with empty implementation
    public static void main(String[] args) {
        Test t = new Test();
        t.wish();

    }
}
